# Generated by Django 4.2.2 on 2023-06-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipoUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ape_paterno', models.CharField(max_length=50)),
                ('ape_materno', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tipousuario')),
            ],
        ),
    ]
