# Generated by Django 4.2.2 on 2023-06-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_tipousuario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ape_materno',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ape_paterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
    ]
