# Generated by Django 4.2.2 on 2023-06-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
